// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv7wlUvOGaxesc1E6gMuCfLscq_dUT-5I',
    appId: '1:135415229642:web:9b6fabf1e2e08ed55e9833',
    messagingSenderId: '135415229642',
    projectId: 'inventario-ibp-2b71d',
    authDomain: 'inventario-ibp-2b71d.firebaseapp.com',
    storageBucket: 'inventario-ibp-2b71d.appspot.com',
    measurementId: 'G-Z1BQLB2W35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXiu_KjCB2hUN4zCBzAynHgVTzfS7FH4M',
    appId: '1:135415229642:android:c3889b49650c88b65e9833',
    messagingSenderId: '135415229642',
    projectId: 'inventario-ibp-2b71d',
    storageBucket: 'inventario-ibp-2b71d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuC6NLUpo2xuwp3lCc0Z3KTuQy6Evwqos',
    appId: '1:135415229642:ios:85017431f6dca7b45e9833',
    messagingSenderId: '135415229642',
    projectId: 'inventario-ibp-2b71d',
    storageBucket: 'inventario-ibp-2b71d.appspot.com',
    iosClientId: '135415229642-eqiv5bku3tjv6jag14gm2q0ljjc60l7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventarioIbp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuC6NLUpo2xuwp3lCc0Z3KTuQy6Evwqos',
    appId: '1:135415229642:ios:b1c5cb81e9be8cc35e9833',
    messagingSenderId: '135415229642',
    projectId: 'inventario-ibp-2b71d',
    storageBucket: 'inventario-ibp-2b71d.appspot.com',
    iosClientId: '135415229642-h9j2m1t278o89pm9c6p6uupvlkherq2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventarioIbp.RunnerTests',
  );
}
